//
//  Prism.Language.swift
//  swift-html-prism
//
//  Created by Coen ten Thije Boonkkamp on 01/09/2025.
//

extension Prism {
    public enum Language: String, Sendable, CaseIterable {
        // Core languages
        case markup = "markup"
        case html = "html"
        case xml = "xml"
        case svg = "svg"
        case mathml = "mathml"
        case ssml = "ssml"
        case atom = "atom"
        case rss = "rss"
        case css = "css"
        case clike = "clike"
        case javascript = "javascript"
        case js = "js"

        // A
        case abap = "abap"
        case abnf = "abnf"
        case actionscript = "actionscript"
        case ada = "ada"
        case agda = "agda"
        case al = "al"
        case antlr4 = "antlr4"
        case g4 = "g4"
        case apacheconf = "apacheconf"
        case apex = "apex"
        case apl = "apl"
        case applescript = "applescript"
        case aql = "aql"
        case arduino = "arduino"
        case ino = "ino"
        case arff = "arff"
        case armasm = "armasm"
        case armAsm = "arm-asm"
        case arturo = "arturo"
        case art = "art"
        case asciidoc = "asciidoc"
        case adoc = "adoc"
        case aspnet = "aspnet"
        case asm6502 = "asm6502"
        case asmatmel = "asmatmel"
        case autohotkey = "autohotkey"
        case autoit = "autoit"
        case avisynth = "avisynth"
        case avs = "avs"
        case avroIdl = "avro-idl"
        case avdl = "avdl"
        case awk = "awk"
        case gawk = "gawk"

        // B
        case bash = "bash"
        case sh = "sh"
        case shell = "shell"
        case basic = "basic"
        case batch = "batch"
        case bbcode = "bbcode"
        case shortcode = "shortcode"
        case bbj = "bbj"
        case bicep = "bicep"
        case birb = "birb"
        case bison = "bison"
        case bnf = "bnf"
        case rbnf = "rbnf"
        case bqn = "bqn"
        case brainfuck = "brainfuck"
        case brightscript = "brightscript"
        case bro = "bro"
        case bsl = "bsl"
        case oscript = "oscript"

        // C
        case c = "c"
        case csharp = "csharp"
        case cs = "cs"
        case dotnet = "dotnet"
        case cpp = "cpp"
        case cfscript = "cfscript"
        case cfc = "cfc"
        case chaiscript = "chaiscript"
        case cil = "cil"
        case cilkc = "cilkc"
        case cilkC = "cilk-c"
        case cilkcpp = "cilkcpp"
        case cilkCpp = "cilk-cpp"
        case cilk = "cilk"
        case clojure = "clojure"
        case cmake = "cmake"
        case cobol = "cobol"
        case coffeescript = "coffeescript"
        case coffee = "coffee"
        case concurnas = "concurnas"
        case conc = "conc"
        case csp = "csp"
        case cooklang = "cooklang"
        case coq = "coq"
        case crystal = "crystal"
        case cssExtras = "css-extras"
        case csv = "csv"
        case cue = "cue"
        case cypher = "cypher"

        // D
        case d = "d"
        case dart = "dart"
        case dataweave = "dataweave"
        case dax = "dax"
        case dhall = "dhall"
        case diff = "diff"
        case django = "django"
        case jinja2 = "jinja2"
        case dnsZoneFile = "dns-zone-file"
        case dnsZone = "dns-zone"
        case docker = "docker"
        case dockerfile = "dockerfile"
        case dot = "dot"
        case gv = "gv"

        // E
        case ebnf = "ebnf"
        case editorconfig = "editorconfig"
        case eiffel = "eiffel"
        case ejs = "ejs"
        case eta = "eta"
        case elixir = "elixir"
        case elm = "elm"
        case etlua = "etlua"
        case erb = "erb"
        case erlang = "erlang"
        case excelFormula = "excel-formula"
        case xlsx = "xlsx"
        case xls = "xls"

        // F
        case fsharp = "fsharp"
        case factor = "factor"
        case `false` = "false"
        case firestoreSecurityRules = "firestore-security-rules"
        case flow = "flow"
        case fortran = "fortran"
        case ftl = "ftl"

        // G
        case gml = "gml"
        case gap = "gap"
        case gcode = "gcode"
        case gdscript = "gdscript"
        case gedcom = "gedcom"
        case gettext = "gettext"
        case po = "po"
        case gherkin = "gherkin"
        case git = "git"
        case glsl = "glsl"
        case gn = "gn"
        case gni = "gni"
        case linkerScript = "linker-script"
        case ld = "ld"
        case go = "go"
        case goModule = "go-module"
        case goMod = "go-mod"
        case gradle = "gradle"
        case graphql = "graphql"
        case groovy = "groovy"

        // H
        case haml = "haml"
        case handlebars = "handlebars"
        case hbs = "hbs"
        case mustache = "mustache"
        case haskell = "haskell"
        case hs = "hs"
        case haxe = "haxe"
        case hcl = "hcl"
        case hlsl = "hlsl"
        case hoon = "hoon"
        case http = "http"
        case hpkp = "hpkp"
        case hsts = "hsts"
        case hydra = "hydra"

        // I
        case ichigojam = "ichigojam"
        case icon = "icon"
        case icuMessageFormat = "icu-message-format"
        case idris = "idris"
        case idr = "idr"
        case ignore = "ignore"
        case gitignore = "gitignore"
        case hgignore = "hgignore"
        case npmignore = "npmignore"
        case inform7 = "inform7"
        case ini = "ini"
        case io = "io"

        // J
        case j = "j"
        case java = "java"
        case javadoc = "javadoc"
        case javadoclike = "javadoclike"
        case javastacktrace = "javastacktrace"
        case jexl = "jexl"
        case jolie = "jolie"
        case jq = "jq"
        case jsExtras = "js-extras"
        case jsTemplates = "js-templates"
        case jsdoc = "jsdoc"
        case json = "json"
        case webmanifest = "webmanifest"
        case json5 = "json5"
        case jsonp = "jsonp"
        case jsstacktrace = "jsstacktrace"
        case jsx = "jsx"
        case julia = "julia"

        // K
        case keepalived = "keepalived"
        case keyman = "keyman"
        case kotlin = "kotlin"
        case kt = "kt"
        case kts = "kts"
        case kumir = "kumir"
        case kum = "kum"
        case kusto = "kusto"

        // L
        case latex = "latex"
        case tex = "tex"
        case context = "context"
        case latte = "latte"
        case less = "less"
        case lilypond = "lilypond"
        case ly = "ly"
        case liquid = "liquid"
        case lisp = "lisp"
        case emacs = "emacs"
        case elisp = "elisp"
        case emacsLisp = "emacs-lisp"
        case livescript = "livescript"
        case llvm = "llvm"
        case log = "log"
        case lolcode = "lolcode"
        case lua = "lua"

        // M
        case magma = "magma"
        case makefile = "makefile"
        case markdown = "markdown"
        case md = "md"
        case markupTemplating = "markup-templating"
        case mata = "mata"
        case matlab = "matlab"
        case maxscript = "maxscript"
        case mel = "mel"
        case mermaid = "mermaid"
        case metafont = "metafont"
        case mizar = "mizar"
        case mongodb = "mongodb"
        case monkey = "monkey"
        case moonscript = "moonscript"
        case moon = "moon"

        // N - Z (continuing with same pattern...)
        case n1ql = "n1ql"
        case n4js = "n4js"
        case n4jsd = "n4jsd"
        case naniscript = "naniscript"
        case nani = "nani"
        case nasm = "nasm"
        case neon = "neon"
        case nevod = "nevod"
        case nginx = "nginx"
        case nim = "nim"
        case nix = "nix"
        case nsis = "nsis"
        case objectivec = "objectivec"
        case objc = "objc"
        case ocaml = "ocaml"
        case odin = "odin"
        case opencl = "opencl"
        case openqasm = "openqasm"
        case qasm = "qasm"
        case oz = "oz"
        case parigp = "parigp"
        case parser = "parser"
        case pascal = "pascal"
        case objectpascal = "objectpascal"
        case pascaligo = "pascaligo"
        case psl = "psl"
        case pcaxis = "pcaxis"
        case px = "px"
        case peoplecode = "peoplecode"
        case pcode = "pcode"
        case perl = "perl"
        case php = "php"
        case phpdoc = "phpdoc"
        case phpExtras = "php-extras"
        case phtmll = "phtml"
        case plsql = "plsql"
        case powerquery = "powerquery"
        case pq = "pq"
        case mscript = "mscript"
        case powershell = "powershell"
        case processing = "processing"
        case prolog = "prolog"
        case promql = "promql"
        case properties = "properties"
        case protobuf = "protobuf"
        case pug = "pug"
        case puppet = "puppet"
        case pure = "pure"
        case purebasic = "purebasic"
        case pbfasm = "pbfasm"
        case purescript = "purescript"
        case purs = "purs"
        case python = "python"
        case py = "py"
        case q = "q"
        case qml = "qml"
        case qore = "qore"
        case qs = "qs"
        case qsharp = "qsharp"
        case r = "r"
        case racket = "racket"
        case rkt = "rkt"
        case raku = "raku"
        case reason = "reason"
        case regex = "regex"
        case rego = "rego"
        case renpy = "renpy"
        case rpy = "rpy"
        case rescript = "rescript"
        case res = "res"
        case rest = "rest"
        case rip = "rip"
        case roboconf = "roboconf"
        case robotframework = "robotframework"
        case robot = "robot"
        case ruby = "ruby"
        case rb = "rb"
        case rust = "rust"
        case sas = "sas"
        case sass = "sass"
        case scss = "scss"
        case scala = "scala"
        case scheme = "scheme"
        case shellSession = "shell-session"
        case shSession = "sh-session"
        case shellsession = "shellsession"
        case smali = "smali"
        case smalltalk = "smalltalk"
        case smarty = "smarty"
        case sml = "sml"
        case smlnj = "smlnj"
        case solidity = "solidity"
        case sol = "sol"
        case solutionFile = "solution-file"
        case sln = "sln"
        case soy = "soy"
        case sparql = "sparql"
        case rq = "rq"
        case splunkSpl = "splunk-spl"
        case sqf = "sqf"
        case sql = "sql"
        case squirrel = "squirrel"
        case stan = "stan"
        case stata = "stata"
        case stylus = "stylus"
        case supercollider = "supercollider"
        case sclang = "sclang"
        case swift = "swift"
        case systemd = "systemd"
        case t4Cs = "t4-cs"
        case t4 = "t4"
        case t4Vb = "t4-vb"
        case t4Templating = "t4-templating"
        case tap = "tap"
        case tcl = "tcl"
        case textile = "textile"
        case toml = "toml"
        case tremor = "tremor"
        case trickle = "trickle"
        case troy = "troy"
        case tsx = "tsx"
        case tt2 = "tt2"
        case turtle = "turtle"
        case trig = "trig"
        case twig = "twig"
        case typescript = "typescript"
        case ts = "ts"
        case typoscript = "typoscript"
        case tsconfig = "tsconfig"
        case unrealscript = "unrealscript"
        case uscript = "uscript"
        case uc = "uc"
        case uorazor = "uorazor"
        case uri = "uri"
        case url = "url"
        case v = "v"
        case vala = "vala"
        case vbnet = "vbnet"
        case velocity = "velocity"
        case verilog = "verilog"
        case vhdl = "vhdl"
        case vim = "vim"
        case visualBasic = "visual-basic"
        case vb = "vb"
        case vba = "vba"
        case warpscript = "warpscript"
        case wasm = "wasm"
        case webIdl = "web-idl"
        case wgsl = "wgsl"
        case wiki = "wiki"
        case wolfram = "wolfram"
        case mathematica = "mathematica"
        case nb = "nb"
        case wl = "wl"
        case wren = "wren"
        case xeora = "xeora"
        case xeoracube = "xeoracube"
        case xmlDoc = "xml-doc"
        case xojo = "xojo"
        case xquery = "xquery"
        case yaml = "yaml"
        case yml = "yml"
        case yang = "yang"
        case zig = "zig"

        public var cdnComponentPath: String {
            "prism-\(rawValue).min.js"
        }

        public var className: String {
            "language-\(rawValue)"
        }
    }
}

// Language groups
extension Prism.Language {
    public static let webLanguages: [Self] = [
        .html, .css, .javascript, .typescript, .jsx, .tsx,
    ]

    public static let shellLanguages: [Self] = [
        .bash, .shell, .powershell, .batch,
    ]

    public static let dataLanguages: [Self] = [
        .json, .yaml, .xml, .csv, .toml,
    ]

    public static let cFamily: [Self] = [
        .c, .cpp, .csharp, .objectivec,
    ]

    public static let jvmLanguages: [Self] = [
        .java, .kotlin, .scala, .groovy,
    ]

    public static let functionalLanguages: [Self] = [
        .haskell, .elm, .fsharp, .ocaml, .lisp, .clojure, .erlang, .elixir,
    ]

    public static let scriptingLanguages: [Self] = [
        .python, .ruby, .perl, .lua, .php,
    ]

    public static let systemLanguages: [Self] = [
        .rust, .go, .zig, .nim, .d,
    ]

    public static let mobileLanguages: [Self] = [
        .swift, .kotlin, .objectivec, .java, .dart,
    ]
}
